@startuml
enum com.example.tutorialgame.engine.ui.effects.impcateffects.ImpactEffectType {
+  WHITE_CIRCLE
+  ORANGE_CIRCLE
+  SPARK
+  SPARK2
+  SLASH
+  DUST_CLOUD_LANDING
- Bitmap[] impactSpr
- int frameCount
- boolean rotationable
+ Bitmap getSprite(int)
+ int getFrameCount()
+ int getAnimSpeed()
+ boolean isRotationable()
+ boolean isImpactOnly()
}


class com.example.tutorialgame.cloud.document.ProgressDoc {
- {static} String KEY_ROOT
- {static} String KEY_XP
- {static} String KEY_LEVEL
- {static} String KEY_UPGRADE_POINTS
- {static} String KEY_UPGRADES_DONE
- {static} String KEY_DAYS_LOGGED
- {static} String KEY_ENEMIES_KILLED
- {static} String KEY_QUESTS_DONE
- {static} String KEY_MET_CHARS
- {static} String KEY_LAST_LOGIN
- int xp
- int level
- int upgradePoints
- int upgradesDone
- int daysLoggedIn
- int enemiesDefeated
- int questsCompleted
- String lastLoginDate
- List<String> metCharacters
- SimpleDateFormat dateFormat
# void parseData(Map<String,Object>)
# String getDocName()
+ void createProfile()
+ void updateLogin()
+ void updateXp(int)
- void checkLevelUp()
+ void registerEncounter(String)
- void increaseLevel()
+ int neededXpForLevelUp()
+ void increaseUpgradePoints(int)
+ void decreaseUpgradePoints(int)
+ void increaseUpgradeDone()
+ void addUpgradesDone(int)
+ void increaseDaysLoggedIn()
+ void increaseEnemiesDefeated()
+ void increaseQuestsCompleted()
+ int getUpgradePoints()
+ int getXp()
+ int getLevel()
+ int getUpgradesDone()
+ int getDaysLoggedIn()
+ int getEnemiesDefeated()
+ int getQuestsCompleted()
}


class com.example.tutorialgame.entities.characters.nonenemies.allies.Blacksmith {
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

class com.example.tutorialgame.engine.ui.PlayingUI {
- {static} boolean SHOW_UI
- Joystick joystick
- CircleButton btnJump
- Player player
- OverWorld overWorld
- RectF facesetHitbox
- Bitmap currentFrame
- int facesetPointerId
- boolean facesetPressed
- boolean startFace
- float facesetBaseRotation
- {static} float FRAME_OFFSET
- {static} float CENTER_FRAME_OFFSET
- boolean rotating
- float rotationAngle
- float rotationFrom
- float rotationTo
- float rotationElapsed
- CoinDisplay coinDisplay
- StaminaDisplay staminaDisplay
- HealthDisplay healthDisplay
- LevelUpEffect levelUpEffect
- void setListeners()
+ void update(double)
- void updateButtons()
- void startRotateTo(float)
+ void draw(Canvas)
- void drawFaceset(Canvas)
- Bitmap getActiveFace()
- void drawCircleFrame(Canvas)
+ void touchEvents(MotionEvent)
- void handleFacesetTouch(MotionEvent)
+ void resetJoystickButton()
+ void onClick(BaseButton)
+ {static} void setShowUI(boolean)
}


class com.example.tutorialgame.managers.DialogueManager {
- {static} String TAG
- {static} Gson gson
- {static} Type STRING_LIST_TYPE
- {static} Map<String,JsonElement> dialogueCache
- {static} String loadedLanguage
+ {static} void checkLanguageSync()
+ {static} List<String> resolveDialogue(String)
- {static} JsonElement loadCharacterFile(String,String)
- {static} List<String> parseDialogueElement(JsonElement)
- {static} boolean isConditionMet(JsonElement)
}


class com.example.tutorialgame.engine.ui.circleframes.FramesAdapter {
- CircleFrameSeries series
- List<CircleFrames> frames
- String seriesName
- int seriesPosition
- String selectedFrameName
- FrameSeriesAdapter.FrameSelectionListener listener
- OnDataChangedListener dataChangedListener
+ FrameUnlockCondition.Condition getConditionType()
+ void refreshLockedItemsStatus()
+ FrameViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(FrameViewHolder,int)
+ int getItemCount()
- String getProgressDescription(Context)
- String getProgress(int)
- String getTitle(Context,int)
}


interface com.example.tutorialgame.engine.ui.circleframes.FramesAdapter$OnDataChangedListener {
~ void onDataChanged(int)
}

class com.example.tutorialgame.engine.ui.circleframes.FramesAdapter$FrameViewHolder {
- ImageView frameImage
- ImageView lockIcon
- ImageView glowEffect
- void bind(CircleFrames,boolean,int,FrameSeriesAdapter.FrameSelectionListener)
- void setupLockedState(int,Context)
- void showBalloonPopup(View,int)
- void handleUnlock(int)
}


class com.example.tutorialgame.quest.QuestType {
+ Type type
+ String targetId
}

enum com.example.tutorialgame.quest.Type {
+  DIALOGUE_WITH
+  COLLECT_ITEM
+  ENTER_ZONE
+  DEFEAT_ENEMY
}

class com.example.tutorialgame.managers.MapManager {
- {static} String TAG
- {static} GameMap currentMap
- {static} Map<String,GameMap> loadedMaps
- OverWorld overWorld
- Random random
- List<WeatherEffect> weatherEffects
- RectF viewRect
- TileRenderer tileRenderer
+ void initWeatherForCurrentMap()
+ void updateWeather(double)
+ void drawWeather(Canvas,WeatherEffect.RenderOrder)
- PointF getRandomViewPosition()
+ void updateWorldEntities(Player,double)
+ void drawXpEffects(Canvas)
+ void updateViewRect()
+ void drawTiles(Canvas)
+ Doorway isPlayerOnDoorway(RectF)
+ void changeMap(Doorway)
+ {static} GameMap getCurrentMap()
+ {static} void clearCache()
+ {static} void reloadAllLoadedMaps()
+ void resetWorldForRestart(OnMapReadyListener)
+ {static} GameMap getMapByName(String)
+ {static} Character getCharacterById(String,String)
- {static} void connectDoorwaysForMap(GameMap)
+ {static} void initStartingWorld()
+ RectF getViewRect()
}


interface com.example.tutorialgame.managers.MapManager$OnMapReadyListener {
~ void onMapReady(GameMap)
}

class com.example.tutorialgame.gamestates.UpgradeState {
- {static} int LINE_ANIM_SPEED
- {static} int BLUR_STEPS
- {static} BlurMaskFilter[] BLUR_FILTERS
- {static} int BLUR_UPDATE_MS
- int blurIndex
- long blurElapsed
- Paint blurPaint
- RectF screenRect
- {static} int STAMINA_MAX_PER_ICON
- {static} int FADE_WIDTH
- {static} float STAGGER_FACTOR
- AnimationComponent lineAnimation
- Bitmap[] lineSprites
- float lineX
- RectF modelHitbox
- Bitmap modelBmp
- float firstTouch
- boolean isModelTouch
- float heartX
- RectButton btnReturn
- CircleButton btnApplyChanges
- CustomUpgrade[] upgrades
- CustomUpgrade healthUpgrade
- float startX
- Bitmap pointsBoxBmp
- int pointsLeft
- TextRenderer pointsRenderer
- float scrollX
- boolean isDragging
- float dragThreshold
- Rect upgradeClipArea
- XpDisplay xpDisplay
- Paint fadePaint
- Bitmap staminaProgress
- float staminaXAdjustment
- Rect tempSrcRect
- RectF tempDstRect
- void init()
- void createLine()
- void createUI()
+ void onEnter()
+ void onExit()
+ void update(double)
- void updateBlurEffect()
+ void render(Canvas)
+ void touchEvents(MotionEvent)
- void handleScrolling(MotionEvent)
- void handleBalloonDismissal(MotionEvent)
- void handleModelRotation(MotionEvent)
- void updateModelDirection(int)
- void drawHearts(Canvas)
- void drawStamina(Canvas)
- void drawClippedStamina(Canvas,Bitmap,float,float,int,Paint)
- Bitmap getHeartIcon(int)
- void updateModel()
+ boolean onUpgradeChanged(CustomUpgrade,int)
- void applyChanges()
- void drawModel(Canvas)
}


class com.example.tutorialgame.engine.ui.effects.LevelUpEffect {
- int currentLevel
- Bitmap circle
- float x
- float offset
- long lastUpdate
- TextRenderer levelPaint
- boolean played
+ void update(double)
- void setPositions()
- void slideAnimation(double)
+ void draw(Canvas)
}


class com.example.tutorialgame.engine.ui.displays.CoinDisplay {
- Bitmap coinImg
- NinePatchDrawable background
- TextRenderer textPaint
- int coinsCount
- float offset
- long lastUpdate
+ {static} float xDestination
- void setPositions()
+ void update(double)
- void slideAnimation(double)
+ void draw(Canvas)
}


class com.example.tutorialgame.managers.objectpool.ObjectPool {
- T[] pool
- Supplier<T> factory
- int top
+ T acquire()
+ void release(T)
+ void clear()
}


class com.example.tutorialgame.entities.characters.Player {
- long attackStartTime
- int attackSpeed
- PointF lastTouchDiff
- Character currentSpeaker
- int lastAniIndex
- List<String> interiorDialogue
- boolean pendingDialogue
- WorldAnimationEffect landingDustEffect
+ void reset()
+ void refreshStats()
+ void update(double,GameMap)
+ void draw(Canvas)
- void handleFootstepSound(GameMap)
- void playFootstepSound(GameMap)
+ void setMovementInput(boolean,PointF)
+ void setAttacking(boolean)
+ void setJumping(boolean)
- void checkPlayerAttack(List<Character>,List<BreakableEntity>)
+ void setInteriorDialogue(List<String>)
+ void takeDamage(int,Character)
+ boolean canDamage(Character)
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
- boolean isDistancedFromNPC()
+ void setCurrentSpeaker(Character)
+ Character getCurrentSpeaker()
- void updatePlayerMove(double,GameMap)
- void updatePlayerFaceDir(float,float)
+ boolean hasPendingDialogue()
+ List<String> consumeInteriorDialogue()
}


class com.example.tutorialgame.gamestates.cutscenes.SceneManager {
- List<BaseScene> scenePlaylist
- BaseScene currentScene
- boolean isStartingDialogueAfter
- void buildPlaylist()
+ void playNextRelevantScene()
+ void onSceneFinished()
+ void onEnter()
+ void onExit()
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
}


class com.example.tutorialgame.engine.ui.circleframes.FrameUnlockCondition {
- List<Integer> priceArr
- Condition selectedCondition
+ Condition getSelectedCondition()
+ List<Integer> getPriceArr()
+ int getCurrentAmount()
}


enum com.example.tutorialgame.engine.ui.circleframes.Condition {
+  PURCHASE
+  DAYS
+  ENEMIES_DEFEATED
+  LEVEL
+  BOSSES_DEFEATED
}

class com.example.tutorialgame.entities.foregrounds.statics.StaticObject {
- StaticObjectData objectData
+ StaticObjectData getObjectData()
+ Bitmap getBitmap()
+ float getDrawX()
+ float getDrawY()
+ void draw(Canvas)
}


class com.example.tutorialgame.engine.ui.effects.weathereffects.Cloud {
- {static} Bitmap staticCloudBmp
- {static} PorterDuffColorFilter cloudFilter
- long birthTime
+ RenderOrder getRenderOrder()
# void init(float,float)
+ void update(double)
+ void draw(Canvas)
}


class com.example.tutorialgame.managers.objectpool.ObjectPoolManager {
- {static} int MAX_POOL_SIZE
- {static} BrokenParticle[] particlePool
- {static} int particleTop
- {static} Coin[] coinPool
- {static} int coinTop
- {static} XpEffect[] xpPool
- {static} int xpTop
- {static} Map<String,List<Character>> characterPools
- {static} RespawnTask[] respawnPool
- {static} int respawnTop
+ {static} Character acquireCharacter(String,PointF)
+ {static} void releaseCharacter(Character)
+ {static} BrokenParticle acquireParticle(float,float,Bitmap)
+ {static} void releaseParticle(BrokenParticle)
+ {static} Coin acquireCoin(float,float)
+ {static} void releaseCoin(Coin)
+ {static} XpEffect acquireXpEffect(int,float,float)
+ {static} void releaseXpEffect(XpEffect)
+ {static} RespawnTask acquireRespawnTask(double)
+ {static} void releaseRespawnTask(RespawnTask)
+ {static} void clearAllPools()
}


class com.example.tutorialgame.managers.objectpool.ObjectPoolManager$RespawnTask {
+ double timeLeft
+ void init(double)
}


enum com.example.tutorialgame.entities.foregrounds.breakable.BreakParticlesType {
+  WOOD
+  GRASS
+  ROCK
- Bitmap[] spr
- int sfxId
+ Bitmap getRandomParticle()
+ int getSfxId()
+ int getLevelRequired()
}


interface com.example.tutorialgame.engine.interfaces.StaticEntity {
~ Bitmap getBitmap()
~ float getDrawX()
~ float getDrawY()
~ RectF getHitBox()
}

class com.example.tutorialgame.quest.Quest {
- int taskRes
- String internalId
- QuestType questType
- Runnable onCompleteAction
- int coins
+ boolean isCompleted()
+ void complete()
+ String getTaskString()
+ QuestType getQuestType()
}


class com.example.tutorialgame.ui.fragments.LanguageFragment {
- ImageButton imgBtnClose
- Map<Button,String> langMap
- SharedPreferences spLanguage
- SharedPreferences.Editor languageEditor
# int getLayoutResId()
# void onSetupView(View)
- void initPrefs()
- void bindViews(View)
- void initListeners()
+ void onClick(View)
- void changeLanguage(String,Button)
}


enum com.example.tutorialgame.entities.Weapons {
+  BIG_SWARD
+  CLUB
+  BONE
+  SPEAR
+  HAMMER
+  NULL
- Bitmap weaponInHandImg
- int bottomOffset
- float knockBackForce
- int baseDamage
- ImpactEffectType effectType
- int swingSfx
- {static} int NULL_SIZE
+ Bitmap getWeaponInHandImg()
+ int getWidth()
+ int getHeight()
+ int getBottomOffset()
+ float getKnockBackForce()
+ int getBaseDamage()
+ int getSwingSfx()
+ ImpactEffectType getEffectType()
}


class com.example.tutorialgame.gamestates.menu.menustates.OptionsMenu {
- List<RectButton> buttons
- RectButton btnDone
- void registerButton(RectButton)
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ void onClick(BaseButton)
}


class com.example.tutorialgame.engine.ui.customviews.buttons.rects.RectButton {
- NinePatchDrawable normal
- RectImages rectImages
- NinePatchDrawable getBtnImg()
+ RectF getHitbox()
+ void draw(Canvas)
# boolean isIn(float,float)
}


class com.example.tutorialgame.utils.Other {
+ {static} boolean IsCharacterSeesTarget(Character,Character)
+ {static} int TurnTowardsTarget(float,float,Character)
+ {static} void IntersectCircle(float,float,float,float,float,PointF)
}

class com.example.tutorialgame.engine.ui.effects.lighting.LightSource {
- PointF pos
- float baseRadius
- float currentRadius
- LightType type
- Random random
- float animationTime
- float jitter
- PorterDuffColorFilter outerFilter
- PorterDuffColorFilter innerFilter
- boolean isPureWhite
- int calculateInnerColor(int)
+ void update(double)
+ PointF getPos()
+ float getRadius()
+ PorterDuffColorFilter getOuterFilter()
+ PorterDuffColorFilter getInnerFilter()
+ boolean isPureWhite()
}


enum com.example.tutorialgame.engine.ui.effects.lighting.LightType {
+  STATIC
+  FLICKER
+  PULSE
}

class com.example.tutorialgame.engine.audio.MusicManager {
- {static} String TAG
- {static} long SAVE_DELAY_MS
- {static} MusicManager instance
- Context appContext
- SharedPreferences sp
- MediaPlayer activePlayer
- MediaPlayer fadingPlayer
- int activeResId
- int lastResId
- float musicVolume
- boolean isLooping
- Handler handler
- Runnable saveRunnable
- Runnable fadeRunnable
- boolean isDucked
- {static} float DUCK_VOLUME_MULTIPLIER
+ {static} MusicManager getInstance(Context)
- MediaPlayer createMediaPlayer()
+ void play(int)
- void setupAndPlayNewTrack(int,float)
- void startCrossfade()
+ void duck()
+ void unDuck()
+ void pause()
+ void stop()
+ int getCurrentResId()
+ int getLastResId()
+ boolean isPlaying()
+ void setVolume(float,boolean)
+ float getVolume()
+ void setVolume(float)
+ void setLooping(boolean)
+ void release()
+ void persistVolumeNow()
- float clamp(float)
}


class com.example.tutorialgame.environments.GameMap {
- int[][] groundIds
- boolean[][] walkableMap
- SurfaceType[][] surfaceTypeMap
- Tiles tilesType
- MapLoadData mapLoadData
- ArrayList<StaticObject> staticObjectList
- ArrayList<Doorway> doorwayArrayList
- ArrayList<Character> characterArrayList
- List<XpEffect> xpEffectList
- List<AnimatedObject> animatedEntities
- List<BreakableEntity> breakableEntities
- List<LightSource> lightSources
- int ambientDarkness
- String spawnType
- int minMonsters
- int musicRes
- List<Point> walkableTiles
- List<ObjectPoolManager.RespawnTask> respawnQueue
- Random rnd
- Player player
- List<Entity> drawableList
- List<Entity> pendingAddition
- String fileName
- List<TilesetData> tilesets
- boolean hasEffects
- void findWalkableTiles()
- void loadAllEntities(MapLoadData)
- void updateDrawableList()
+ void update(double,Player)
- void handleDynamicSpawning(double)
- boolean spawnNewMonster(int)
- boolean spawnAtMinimumDistance(int)
+ MapLoadData getMapLoadData()
+ List<LightSource> getLightSources()
+ int getAmbientDarkness()
+ List<Entity> getDrawableList()
+ ArrayList<Character> getCharacterArrayList()
+ List<BreakableEntity> getBreakableEntities()
+ ArrayList<Doorway> getDoorwayArrayList()
+ List<XpEffect> getXpList()
+ boolean hasLeavesEffect()
+ boolean hasCloudsEffect()
+ Player getPlayer()
+ String getFileName()
+ Tiles getGround()
+ int getMusicRes()
+ void setMusicRes(int)
+ void setPlayer(Player)
+ void removePlayer()
+ void addCharacter(Character)
+ void removeCharacter(String)
+ void processPendingEntities()
+ void addCoin(Coin)
+ void addXp(XpEffect)
+ void addDoorway(Doorway)
+ int getGroundIds(int,int)
+ int getWallLayerID(int,int)
+ int getCollisionLayerID(int,int)
+ int getArrayWidth()
+ int getArrayHeight()
+ int getMapWidth()
+ int getMapHeight()
+ boolean isTileWalkable(int,int)
- void loadStaticObjects(List<ObjectData>,Class<T>,boolean)
- void initWalkableMap()
- void initSurfaceMap()
+ SurfaceType getSurfaceTypeAt(int,int)
+ String getTileProperty(int,String)
+ Doorway getDoorwayByName(String)
+ void reload()
+ int getRawResourceIdByName(String)
+ void setSpawnType(String)
+ void setMinMonsters(int)
+ void spawnMonsterOnPlayer(int)
+ boolean hasEffects()
}


class com.example.tutorialgame.gamestates.cutscenes.scenes.Intro {
+ void onEnter()
}

class com.example.tutorialgame.utils.TmxLoaderUtils {
- {static} String TAG
+ {static} MapLoadData loadMapFromTMX(String)
- {static} TilesetData parseTileset(Element)
- {static} int[][] parseTileLayer(Document,String,List<TilesetData>)
- {static} Element findLayerElement(Document,String)
- {static} int findFirstGidForGid(int,List<TilesetData>)
- {static} List<ObjectData> parseObjectLayer(Document,String)
}


class com.example.tutorialgame.utils.CollisionUtils {
+ {static} boolean areTilesWalkable(Point[],GameMap)
+ {static} void setTileCords(RectF,float,float,Point[])
+ {static} void setTileIds(int[],int[],Point[],GameMap)
+ {static} float getDistance(float,float,float,float)
+ {static} boolean isWithinRange(float,float,float,float,float)
+ {static} boolean isWithinMapBounds(int,int,GameMap)
}

class com.example.tutorialgame.engine.ui.DialoguePanel {
- PanelState currentState
- Character currentSpeaker
- Bitmap faceSet
- Bitmap dialogBox
- String speakerName
- TextRenderer namePaint
- float targetY
- {static} float SLIDE_SPEED
- float offsetY
- CircleButton btnNext
- DialogState dialogState
- char[] fullLineChars
- String visibleText
- int charIndex
- float timeSinceLastChar
- {static} float TIME_PER_CHAR
- {static} float SHORT_BREAK
- {static} float LONG_BREAK
- float dialogueTextX
- int dialogueTextWidth
- int voiceRes
+ void update(double)
- void updateTypewriter(double)
- float getDelayForChar(char)
- boolean isPunctuation(char)
+ void draw(Canvas)
+ boolean eventHandler(MotionEvent)
- void advanceDialogue()
+ void startDialogue(Character)
- void startNewLine(String)
- void setSpeakerData(Character)
- void finishTyping()
}


enum com.example.tutorialgame.engine.ui.PanelState {
+  HIDDEN
+  ENTERING
+  TYPING
+  WAITING
+  EXITING
}

class com.example.tutorialgame.managers.CameraManager {
- {static} float offsetX
- {static} float lookAtX
- {static} float MIN_ZOOM
- {static} float finalZoom
- {static} float MIN_LERP_FACTOR
- {static} float lerpFactor
- {static} float mapWidth
- {static} Random random
- {static} float shakeDuration
- {static} boolean CAM_SHAKE
- {static} float shakeOffsetX
- {static} SharedPreferences sp
+ {static} void lookAt(float,float,double)
- {static} void updateShake(double)
- {static} void clampLookAt()
+ {static} void setMapSize(float,float)
+ {static} void startShake(float,float)
+ {static} void stopShake()
+ {static} void setZoomFromProgress(float)
+ {static} void setTempZoom(float)
+ {static} void setLerpFactorFromProgress(float)
+ {static} float getNormalizedZoom()
+ {static} float getNormalizedLerpFactor()
+ {static} void setCamShake(boolean)
+ {static} float getFinalZoom()
+ {static} float getTempZoom()
+ {static} float getOffsetX()
+ {static} float getOffsetY()
+ {static} float getLookAtX()
+ {static} float getLookAtY()
}


abstract class com.example.tutorialgame.entities.characters.enemies.Enemy {
}
class com.example.tutorialgame.ui.activities.GameActivity {
- GamePanel gamePanel
- BroadcastReceiver receiveCall
# void onCreate(Bundle)
# void onResume()
# void onPause()
# void onDestroy()
}


enum com.example.tutorialgame.entities.foregrounds.statics.Items {
+  EMPTY_POT
+  MEDIPACK
+  FISH
~ Bitmap image
+ Bitmap getBitmap()
+ int getHitboxWidth()
+ int getHitboxHeight()
+ int getHitboxRoof()
}


class com.example.tutorialgame.cloud.document.ProfileDoc {
- {static} String KEY_ROOT
- {static} String KEY_NICKNAME
- {static} String KEY_EMAIL
- {static} String KEY_LAST_LOGIN
- {static} String KEY_LAST_SLOT
- String nickname
- String email
- String lastLoginDate
- int lastSelectedSlot
- SimpleDateFormat dateFormat
# void parseData(Map<String,Object>)
# String getDocName()
+ void createProfile(String,String)
+ void updateLogin()
+ Task<Void> updateLastSelectedSlot(int)
+ int getLastSelectedSlot()
+ String getNickname()
+ String getEmail()
+ String getField(Field)
+ void updateNickname(String)
}


enum com.example.tutorialgame.cloud.document.Field {
+  EMAIL
+  NICKNAME
}

class com.example.tutorialgame.engine.ui.effects.impcateffects.TapEffect {
- {static} long TOTAL_DURATION_MS
- ImpactEffectType tapType
- long startTime
- long elapsed
+ void show(Canvas,float,float)
+ void resetEffect()
+ void setTapType(ImpactEffectType)
+ long getElapsed()
}


class com.example.tutorialgame.gamestates.cutscenes.scenes.SkeletonArise {
+ void onExit()
}

class com.example.tutorialgame.engine.ui.circleframes.CircleFrameSeries {
- int seriesName
- List<CircleFrames> frames
- FrameUnlockCondition condition
+ String getSeriesName()
+ List<CircleFrames> getFrames()
+ boolean checkCondition(int)
+ FrameUnlockCondition getCondition()
}


class com.example.tutorialgame.engine.ui.effects.WorldAnimationEffect {
- ImpactEffectType type
- PointF pos
- AnimationComponent animator
- Matrix matrix
- boolean active
- float rotation
+ void init(ImpactEffectType,float,float)
+ void init(ImpactEffectType,float,float,float)
+ void update()
+ void draw(Canvas)
+ void setPos(float,float)
+ void setRotation(float)
+ boolean isActive()
}


class com.example.tutorialgame.entities.characters.nonenemies.allies.BestFriend {
+ void updatePosAccordingToStory()
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

enum com.example.tutorialgame.entities.characters.GameCharacters {
+  PLAYER
+  BEST_FRIEND
+  BLACK_KNIGHT
+  WHITE_KNIGHT
+  SKELETON
+  BLACKSMITH
+  FATHER
+  MASTER
+  FIGHTER_RED
+  FIGHTER_WHITE
+  EYE_MONSTER
- Bitmap[][] normalSprites
- Bitmap faceSet
- float viewDistance
- int nameId
- float mass
+ {static} Character createCharacter(String,PointF)
+ int getVoiceRes()
+ int getHeight()
+ int getWidth()
+ Bitmap getSprite(int,int)
+ Bitmap getRageSprites(int,int)
+ boolean hasRage()
+ Bitmap getFaceSet()
+ float getViewDistance()
+ float getMass()
+ void setViewDistance(float)
+ String getName()
}


class com.example.tutorialgame.gamestates.playing.PlayingManager {
- OverWorld overWorld
- DialogState dialogState
- PlayingState currentPlayingState
+ void onEnter()
+ void onExit()
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
- void initPlayingState()
+ void setCurrentPlayingState(PlayingState)
+ void setDialogState(Character)
+ void setCustomDialogState(Character,List<String>)
+ void continueDialog()
+ OverWorld getOverWorld()
}


enum com.example.tutorialgame.gamestates.playing.PlayingState {
+  OVER_WORLD
+  DIALOG
}

class com.example.tutorialgame.ui.activities.LauncherActivity {
- {static} String TAG
- DrawerLayout drawerLayout
- View settingsContainer
- Button btnPlay
- ImageButton imgBtnMenu
- ImageView ivPic
- FrameLayout profileContainer
- View dimBackground
# void onCreate(Bundle)
- void initViews()
- void initListeners()
- void setProfileBackground()
- void setFragmentDrawer()
+ void onClick(View)
- void openProfileFragment()
- void closeProfileFragment()
# void setupBackPressHandler()
}


class com.example.tutorialgame.engine.ui.displays.StaminaDisplay {
- Player player
- {static} Bitmap progressBmp
- {static} int ICON_WIDTH
- {static} float SPACING
- {static} int MAX_PER_ICON
- float progressXAdjustment
- Paint flashPaint
- float xOffset
- int lastMaxStamina
- int currentStaminaCache
- int prevStaminaCache
- float alphaCache
- int iconsCount
- float[] xPositions
- Rect[] progressSrcRects
- Rect[] progressDstRects
- Rect[] flashSrcRects
- Rect[] flashDstRects
- boolean[] drawProgress
- boolean[] drawFlash
+ void update()
- void initArrays(int)
- void recalculateRects(int,int,float)
+ void draw(Canvas)
}


enum com.example.tutorialgame.entities.foregrounds.statics.Natures {
+  DEAD_TREE
+  DARK_TREE
~ Bitmap natureImg
~ int width
~ int hitboxRoof
+ int getHitboxHeight()
+ int getHitboxWidth()
+ Bitmap getBitmap()
+ int getHitboxRoof()
}


abstract class com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral {
- {static} long TIME_TO_FORGET
+ void update(double,GameMap)
+ void checkCharacterDead(Character)
# void putCharInBadBoyList(Character)
}


class com.example.tutorialgame.entities.foregrounds.breakable.BreakableEntity {
- State currentState
- BreakableType type
- List<BrokenParticle> activeParticles
- Random rnd
- float respawnProgress
- {static} float RESPAWN_ANIM_DURATION
- float respawnTimer
- Paint paint
- RectF destRect
+ boolean handleHit()
+ void update(double)
- void updateParticles(double)
+ void draw(Canvas)
- void drawRespawnAnimation(Canvas)
}


enum com.example.tutorialgame.entities.foregrounds.breakable.State {
+  INTACT
+  PIECES_FLYING
+  WAITING_TO_RESPAWN
+  RESPAWNING
}

abstract class com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton {
- {static} BaseButton exclusiveOwner
# RectF hitbox
# boolean pushed
# int pointerId
# boolean vibe
# PressType pressType
- OnClickListener onClickListener
+ void setOnClickListener(OnClickListener)
+ {static} void releaseExclusiveOwner()
+ boolean isPushed(int)
+ void setPushed(boolean,int)
+ void setEnabled(boolean)
# {abstract}boolean isIn(float,float)
# {abstract}void draw(Canvas)
+ boolean eventHandler(MotionEvent)
- int findPointerIndex(MotionEvent,int)
# RectF getHitbox()
}


interface com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton$OnClickListener {
~ void onClick(BaseButton)
}

enum com.example.tutorialgame.engine.ui.customviews.buttons.PressType {
+  ON_DOWN
+  ON_UP
}

class com.example.tutorialgame.entities.foregrounds.animated.AnimatedObject {
# AnimationComponent animation
# Bitmap[] sprites
+ void update(double,Player)
+ void draw(Canvas)
}


class com.example.tutorialgame.quest.ComplexQuest {
- List<Quest> subQuests
- int titleRes
+ Quest getCurrentSubQuest()
+ boolean isAllCompleted()
+ int getTitleRes()
}


class com.example.tutorialgame.engine.ui.displays.HealthDisplay {
- Player player
- float xOffset
- Paint flashPaint
- {static} float SPACING
+ void draw(Canvas)
- void drawCracksForHeart(Canvas,float,int,float)
- Bitmap getHeartIcon(int)
- Bitmap getCrackIcon(int)
}


enum com.example.tutorialgame.environments.Tiles {
+  OUTSIDE
+  INSIDE
+  WALLS
- Bitmap[] sprites
+ Bitmap getSprite(int)
}


abstract class com.example.tutorialgame.entities.Entity {
# RectF hitBox
# boolean active
# PointF spawnPos
+ boolean isActive()
+ boolean isCollider()
+ RectF getHitBox()
+ {abstract}void draw(Canvas)
+ int compareTo(Entity)
}


class com.example.tutorialgame.gamestates.DeathScreen {
- RectButton btnReplay
- NinePatchDrawable background
- int left
- TapEffect tapLT
- int effectOffset
- TextRenderer titlePaint
- String currentLang
- boolean isMusicPlaying
- void updateTitleMeasurements()
+ void update(double)
- void updateOpeningAnimation(double)
- void updateSparkLoop()
+ void render(Canvas)
- void drawSparks(Canvas)
- void drawBackground(Canvas)
- void drawTitle(Canvas)
+ void touchEvents(MotionEvent)
- void resetAnimation()
+ void onClick(BaseButton)
- String getTitle()
}


class com.example.tutorialgame.entities.characters.nonenemies.neutral.BlackKnight {
- boolean angry
+ void update(double,GameMap)
+ void onDialogue()
+ void setAngry(boolean)
# void updateAttackTimer()
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}


class com.example.tutorialgame.environments.Doorway {
- boolean active
- GameMap gameMapLocatedIn
- Doorway doorwayConnectedTo
- PointF doorwayPoint
- String name
+ boolean canBeUsed()
+ String getName()
+ void connectDoorway(Doorway)
+ Doorway getDoorwayConnectedTo()
+ boolean isPlayerInsideDoorway(RectF)
+ boolean isDoorwayActive()
+ void setDoorwayActive(boolean)
+ PointF getPosOfDoorway()
+ GameMap getGameMapLocatedIn()
}


class com.example.tutorialgame.entities.foregrounds.animated.Coin {
- {static} Bitmap staticShadowSprite
- Paint shadowPaint
- JumpComponent jumpComponent
- boolean isHovering
- float hoverOffset
- Random rnd
- boolean flying
- PointF screenPosition
+ void init(float,float)
+ void update(double,Player)
- void pickCoin(Player)
- void goToDestination(double)
- void checkArrivedAtDestination()
+ void draw(Canvas)
- void updateHoverOffset()
- void startHovering()
}


class com.example.tutorialgame.engine.ui.circleframes.FrameData {
- {static} List<CircleFrameSeries> allSeries
+ {static} List<CircleFrameSeries> getAllSeries()
}


abstract class com.example.tutorialgame.cloud.BaseDocument {
# Runnable onFinishedLoading
# DocumentReference docRef
# {abstract}void parseData(Map<String,Object>)
# {abstract}String getDocName()
+ void loadAndCache(UserDataManager.OnDataLoadedListener)
}


class com.example.tutorialgame.cloud.UserDataManager {
- StatsDoc statsDoc
- ProgressDoc progressDoc
- CosmeticDoc cosmeticDoc
- WorldStateDoc worldStateDoc
- int successfulLoads
- boolean hasLoadingFailed
- DocumentReference slotDoc
+ void initializeNewSlotData()
+ void loadAndCache(OnDataLoadedListener)
- void checkAllDataLoaded(OnDataLoadedListener)
+ void deleteData()
+ StatsDoc getPlayerStats()
+ ProgressDoc getProgress()
+ CosmeticDoc getCosmeticDoc()
+ WorldStateDoc getWorldStateDoc()
}


interface com.example.tutorialgame.cloud.UserDataManager$OnDataLoadedListener {
~ void onDataLoadSuccess()
~ void onDataLoadFailed()
}

enum com.example.tutorialgame.entities.foregrounds.statics.Fences {
+  PILLAR_SMALL
+  PILLAR_BIG
+  PILLAR_BIG_CORNER
+  FENCE_FRONT
+  MAINGATE_CLOSE
+  WALL_FRONT
+  WALL_SIDE
+  TOP_LEFT
+  TOP_RIGHT
+  TOP_MIDDLE
~ Bitmap fenceImg
~ int width
~ int hitboxRoof
+ int getHitboxHeight()
+ int getHitboxWidth()
+ Bitmap getBitmap()
+ int getHitboxRoof()
}


class com.example.tutorialgame.entities.characters.nonenemies.allies.Master {
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

enum com.example.tutorialgame.engine.ui.customviews.buttons.circles.CircleImages {
+  JUMP
+  ATTACK
+  UPGRADE
+  DOWNGRADE
+  APPLY
+  RADIO
+  PAUSE
+  NEXT
+  SPEAK
- Bitmap normal
- BaseButton.PressType pressType
+ Bitmap getNormal()
+ Bitmap getPressed()
+ Bitmap getDisabled()
+ int getWidth()
+ int getHeight()
+ BaseButton.PressType getPressType()
}


class com.example.tutorialgame.components.drop.DropEntry {
- int minCoins
- int minXp
- double chance
- Random rnd
+ int getCoinsAmount()
+ int getXpAmount()
}


enum com.example.tutorialgame.engine.ui.customviews.switches.SwitchList {
+  HAPTICS
+  HITBOX
+  UI
+  FPS
+  CAM_SHAKE
- {static} Bitmap checked
- String key
- boolean defValue
- int name
+ String getKey()
+ String getName()
+ boolean getDefValue()
+ Bitmap getChecked()
+ Bitmap getUnChecked()
+ float getWidth()
+ float getHeight()
}


class com.example.tutorialgame.entities.characters.nonenemies.neutral.Father {
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

class com.example.tutorialgame.engine.core.GameConstants {
}
class com.example.tutorialgame.engine.core.GameConstants$Face_Dir {
+ {static} int DOWN
+ {static} int UP
+ {static} int LEFT
+ {static} int RIGHT
}

class com.example.tutorialgame.engine.core.GameConstants$Sprite {
+ {static} int DEFAULT_SIZE
+ {static} int SCALE_MULTIPLIER
+ {static} int TILE_SIZE
+ {static} int HITBOX_SIZE
+ {static} float HITBOX_OFFSET
+ {static} int X_DRAW_OFFSET
+ {static} int Y_DRAW_OFFSET
}

class com.example.tutorialgame.engine.core.GameConstants$Animation {
+ {static} int SPEED
+ {static} int AMOUNT
+ {static} int DEATH_FRAME_INDEX
}

class com.example.tutorialgame.engine.core.GameConstants$View {
+ {static} int SCREEN_WIDTH
+ {static} int SCREEN_HEIGHT
+ {static} float VIEW_MARGIN
+ {static} void initScreenDimensions(int,int)
}


class com.example.tutorialgame.engine.core.GameConstants$Faction {
+ {static} int PLAYER
+ {static} int ALLY
+ {static} int ENEMY
+ {static} int NEUTRAL
}

enum com.example.tutorialgame.gamestates.cutscenes.Scenes {
+  INTRO
+  GETTING_SWORD
+  SKELETON_ARISE
- Bitmap[] frameArr
- String checkPoint
- int musicRes
- boolean dialogueAfter
+ Bitmap[] getFrameArr()
+ String getCheckPoint()
+ int getMusicRes()
+ boolean getDialogueAfter()
}


abstract class com.example.tutorialgame.gamestates.menu.BaseMenu {
# NinePatchDrawable background
# TextRenderer titlePaint
# MenuManager menuManager
- int lastRes
# void drawBackground(Canvas,int)
}


class com.example.tutorialgame.ui.activities.authentication.RegisterActivity {
- TextView tvLoginNow
- Button btnRegister
- TextInputEditText etEmail
- ProgressBar progressBar
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void initViews()
- void initListeners()
- void initTextWatcher()
+ void onClick(View)
- void registerUser()
- void handleRegisterSuccess(String,String,String)
- Intent getSuccessIntent(String,String)
- void sendVerificationEmail()
- void handleRegisterFailure(Exception)
}


enum com.example.tutorialgame.engine.ui.circleframes.CircleFrames {
+  FRAME_00
+  FRAME_01
+  FRAME_02
+  FRAME_03
+  FRAME_04
+  FRAME_05
+  FRAME_06
+  FRAME_07
+  FRAME_08
+  FRAME_09
+  FRAME_10
+  FRAME_11
+  FRAME_12
+  FRAME_13
+  FRAME_14
+  FRAME_15
+  FRAME_16
+  FRAME_17
+  FRAME_18
+  FRAME_19
+  FRAME_20
+  FRAME_21
+  FRAME_22
+  FRAME_23
+  FRAME_24
+  FRAME_25
+  FRAME_26
+  FRAME_27
+  FRAME_28
+  FRAME_29
+  FRAME_30
+  FRAME_31
+  FRAME_32
+  FRAME_33
+  FRAME_34
+  FRAME_35
+  FRAME_36
+  FRAME_37
+  FRAME_38
+  FRAME_39
+  FRAME_40
+  FRAME_41
+  FRAME_42
+  FRAME_43
+  FRAME_44
+  FRAME_45
+  FRAME_46
+  FRAME_47
+  FRAME_48
+  FRAME_49
+  FRAME_50
+  FRAME_51
+  FRAME_52
+  FRAME_53
+  FRAME_54
+  FRAME_55
+  FRAME_56
+  FRAME_57
+  FRAME_58
+  FRAME_59
+  FRAME_60
+  FRAME_61
+  FRAME_62
+  FRAME_63
+  FRAME_64
+  FRAME_65
+  FRAME_66
+  BACKGROUND
+  LOCK
- Bitmap circleFrame
+ Bitmap getCircleFrame()
}


class com.example.tutorialgame.managers.QuestManager {
- {static} List<ComplexQuest> mainStoryLine
- {static} ComplexQuest currentComplexQuest
- {static} Paint lineBase
- {static} TextRenderer titleRenderer
- {static} TextRenderer taskRenderer
- {static} float startX
- {static} void initQuests()
+ {static} void update()
- {static} Quest getCurrentStep()
+ {static} void onDialogueFinished(String)
+ {static} void onEnterZone(String)
+ {static} void onItemCollected(String)
+ {static} void completeCurrentStep()
+ {static} void draw(Canvas)
}


class com.example.tutorialgame.gamestates.cutscenes.BaseScene {
# SceneManager sceneManager
- double frameTimer
- double inputGuardTimer
- TextRenderer nextLabel
- Bitmap[] frames
- int currentFrameIndex
- String checkPointKey
- boolean hasDialogueAfter
- int musicRes
- boolean isSkipping
- Rect screenRect
- {static} float SECONDS_PER_FRAME
- {static} float INPUT_DELAY_SEC
+ void onEnter()
+ void onExit()
+ void update(double)
- void advanceFrame()
- void finishScene()
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ boolean checkCheckPoint()
+ boolean isDialogueAfter()
}


class com.example.tutorialgame.cloud.SaveSlotMetadata {
+ {static} String DOC_NAME
+ {static} String KEY_ROOT
+ {static} String F_NAME
+ {static} String F_CHECKPOINT
+ {static} String F_LEVEL
+ {static} String F_FRAMES_COUNT
- Map<Integer,Slot> slots
# String getDocName()
# void parseData(Map<String,Object>)
- void updateField(int,String,Object)
+ void updateLevel(int,int)
+ void updateFramesCount(int,int)
+ void updateCheckpoint(int,String)
+ void updateSlotName(int,String)
+ void updateSlotMetadata(int,int,int)
+ void resetSlotMetadata(int)
+ Slot getSlot(int)
}


class com.example.tutorialgame.cloud.SaveSlotMetadata$Slot {
+ String slotName
+ String checkpointKey
- int level
+ int framesCount
+ boolean exists
+ int getLevel()
}


class com.example.tutorialgame.components.CombatComponent {
- Character owner
- Weapons weapon
- RectF attackBox
- PointF weaponPos
- float weaponRotation
- WorldAnimationEffect visualEffect
- Matrix drawMatrix
+ void update()
- void updateWeaponTransform()
- void updateAttackBox()
- void updateVisualEffect()
- float calculateEffectRotation()
+ void onSwing()
+ void onImpact()
+ void attack(Character)
+ void draw(Canvas)
- float wepAdjustTop()
- float wepAdjustLeft()
- float wepAdjustBottom()
+ RectF getAttackBox()
+ Weapons getWeapon()
+ void setWeapon(Weapons)
}


class com.example.tutorialgame.engine.ui.effects.XpEffect {
- Bitmap xpImg
- int value
- PointF pos
- long lifeTime
- float floatSpeed
- boolean isActive
- TextRenderer textRenderer
- float offsetY
+ void init(int,float,float)
+ boolean isActive()
+ void update(double)
+ void draw(Canvas)
}


abstract class com.example.tutorialgame.entities.characters.nonenemies.allies.Ally {
+ void update(double,GameMap)
+ boolean canDamage(Character)
}

enum com.example.tutorialgame.engine.ui.CrackIcons {
+  CRACKED_1
+  CRACKED_2
+  CRACKED_3
+  CRACKED_4
- Bitmap icon
+ Bitmap getIcon()
}


interface com.example.tutorialgame.engine.interfaces.GameStateInterface {
~ void update(double)
~ void render(Canvas)
~ void touchEvents(MotionEvent)
}

class com.example.tutorialgame.engine.core.GameLoop {
- {static} String TAG
- Game game
- Thread gameThread
- boolean active
- int FPS
- {static} int TARGET_FPS
- {static} double OPTIMAL_TIME
+ void run()
+ void startGameLoop()
+ void stopGameLoop()
+ int getFPS()
}


class com.example.tutorialgame.cloud.CloudManager {
- DocumentReference userDoc
- ProfileDoc profileDoc
- SaveSlotMetadata slotsMetadata
- UserDataManager activeSlot
- int activeSlotId
+ void loadAccountData(UserDataManager.OnDataLoadedListener)
+ void selectSlot(int,UserDataManager.OnDataLoadedListener)
+ void createNewSlot(int,UserDataManager.OnDataLoadedListener)
+ void deleteInactiveSlot(int,UserDataManager.OnDataLoadedListener)
+ ProfileDoc getProfile()
+ SaveSlotMetadata getSlotsMetadata()
+ UserDataManager getActiveSlot()
+ DocumentReference getUserDoc()
+ int getActiveSlotId()
}


enum com.example.tutorialgame.engine.ui.customviews.radiogroup.RadioGroupList {
+  TAP_EFFECT
- int titleID
- int[] namesID
- String key
+ String getKey()
+ String getName(int)
+ String getTitle()
+ int[] getNamesID()
}


class com.example.tutorialgame.components.StaminaComponent {
- int maxStamina
- float currentStamina
- int prevStamina
- float cooldownTimer
- float cooldownDuration
- boolean staminaLock
- float flashAlpha
- {static} float FLASH_DECREASE_DURATION
- {static} float REGEN_RATE
+ void useStamina(int)
+ void update(double)
+ void reset()
+ boolean hasEnough(int)
+ int getMaxStamina()
+ int getCurrentStamina()
+ int getPrevStamina()
+ float getFlashAlpha()
+ boolean isStaminaLocked()
+ void setMaxStamina(int)
}


class com.example.tutorialgame.engine.ui.customviews.switches.CustomSwitch {
- OnCheckedChangeListener listener
- RectF hitbox
- String key
- SwitchList sw
- TextRenderer paint
- boolean checked
- int baseColorFrom
- long colorAnimStart
- boolean colorAnimating
+ void setOnCheckedChangeListener(OnCheckedChangeListener)
- Bitmap getImg()
+ void draw(Canvas)
+ boolean eventHandler(MotionEvent)
- boolean isIn(MotionEvent)
- void applyColorsImmediate(boolean)
- void startColorTransition(int,int)
- void updateAnimatedColors()
- int lerpColor(int,int,float)
}


interface com.example.tutorialgame.engine.ui.customviews.switches.CustomSwitch$OnCheckedChangeListener {
~ void onCheckedChanged(CustomSwitch,boolean)
}

class com.example.tutorialgame.environments.maploder.TilesetData {
+ int firstGid
+ String name
+ Map<Integer,Map<String,String>> tileProperties
}

class com.example.tutorialgame.ui.fragments.SettingsFragment {
- SeekBar sbMusic
- Button btnLogout
- ImageView ivSound
- SharedPreferences spIcons
- SharedPreferences.Editor iconsEditor
- long lastTouch
- CustomDialog dialogLogout
# int getLayoutResId()
# void onSetupView(View)
- void initPrefs()
- void bindViews(View)
- void initUI()
- void initListeners()
+ boolean onTouch(View,MotionEvent)
+ void onProgressChanged(SeekBar,int,boolean)
- void updateSoundIcon(int)
+ void onStartTrackingTouch(SeekBar)
+ void onStopTrackingTouch(SeekBar)
+ void onClick(View)
}


class com.example.tutorialgame.components.HealthComponent {
- int maxHealth
- int currentHealth
- int prevHealth
- int lastFlashHeartIndex
- float flashAlpha
- {static} float FLASH_DURATION_SEC
+ void takeDamage(int)
+ void heal(int)
+ void update(double)
+ boolean isDead()
+ void reset()
+ int getMaxHealth()
+ int getCurrentHealth()
+ int getPrevHealth()
+ int getLastFlashHeartIndex()
+ float getFlashAlpha()
+ void setMaxHealth(int)
+ void setCurrentHealth(int)
}


interface com.example.tutorialgame.engine.interfaces.BitmapMethods {
~ {static} BitmapFactory.Options options
~ Bitmap getScaledBitmap(Bitmap)
~ Bitmap getMultiplyBitmapSmoth(Bitmap,double)
~ Bitmap getMultiplyBitmapClean(Bitmap,double)
}


enum com.example.tutorialgame.entities.foregrounds.animated.AnimatedType {
+  TORCH_FRONT
+  TORCH_SIDE_LEFT
+  TORCH_SIDE_RIGHT
+  COIN
- Bitmap[] sprites
- int speed
- float width
- boolean collision
+ {static} AnimatedType fromString(String)
+ Bitmap[] getSprites()
+ int getSpeed()
+ float getWidth()
+ float getHeight()
+ boolean isCollision()
}


class com.example.tutorialgame.ui.dialogs.AlertDialogUtils {
+ {static} void showErrorDialogAndRestart(Activity)
+ {static} void resetApp(Activity)
}

enum com.example.tutorialgame.environments.SurfaceType {
+  NONE
+  GRASS
+  DIRT
+  STONE
- int sfxId
+ int getSfxId()
}


abstract class com.example.tutorialgame.ui.dialogs.CustomDialog {
- Dialog customDialog
- TextView tvTitle
- EditText etInput
- Button btnCancel
- LinearLayout layoutDualButtons
- DialogKeys dialogKey
- void initListeners()
- void setVisibles()
- void clearInput()
- void playSound()
+ EditText getEtInput()
+ void show()
+ void dismiss()
+ void onClick()
}


class com.example.tutorialgame.gamestates.playing.playingstates.OverWorld {
- boolean movePlayer
- PointF lastTouchDiff
- MapManager mapManager
- Player player
- PlayingUI playingUI
- PlayingManager playingManager
- boolean doorwayJustPassed
- List<Entity> listOfDrawables
- boolean listOfEntitiesMade
- LightRenderer lightRenderer
- MapTransitionEffect transitionEffect
- Doorway pendingDoorway
+ void onEnter()
+ void update(double)
+ void updateEffects(double)
+ void render(Canvas)
+ void renderWithoutUi(Canvas)
- void setCameraRelativeToPlayer(double)
- void buildEntityList()
+ void resetWorld(Runnable)
- void checkForDoorway()
+ void setDoorwayJustPassed(boolean)
- void checkPlayerDead()
- void drawSortedEntities(Canvas)
+ void setPlayerMoveTrue(PointF)
+ void setPlayerMoveFalse()
+ void touchEvents(MotionEvent)
+ Player getPlayer()
+ PlayingManager getPlayingManager()
}


class com.example.tutorialgame.engine.core.Game {
- SurfaceHolder holder
- GameLoop gameLoop
- TapEffect tapEffect
- PointF lastTouch
- MenuManager menuManager
- PlayingManager playingManager
- DeathScreen deathScreen
- SceneManager sceneManager
- UpgradeState upgradeState
- GameState currentGameState
- SharedPreferences spSettings
- Context context
- TextRenderer fpsRendered
- boolean showFPS
- boolean isResetting
- ExecutorService backgroundExecutor
- {static} GameState nextGameState
+ void update(double)
+ void render()
- void initGameStates()
+ boolean touchEvent(MotionEvent)
+ void restartGame()
+ {static} void setNextGameState(GameState)
- void handleStateChange()
- void initTapEffect()
- void initFPS()
- void drawFPS(Canvas)
+ void startGameLoop()
+ void stopGameLoop()
+ GameState getCurrentGameState()
+ BaseState getStateInstance(GameState)
+ void setTapEffectType(ImpactEffectType)
+ void setShowFPS(boolean)
+ Context getContext()
+ PlayingManager getPlayingManager()
+ void onDestroy()
}


enum com.example.tutorialgame.engine.core.GameState {
+  MENU
+  PLAYING
+  DEATH_SCREEN
+  UPGRADE_STATE
+  CUTSCENE
}

class com.example.tutorialgame.ui.activities.SplashActivity {
- {static} int SPLASH_DELAY
- ImageView ivLogo
- TextView tvAppName
- ObjectAnimator logoAnimator
- float lastVol
- Handler splashHandler
- Runnable statusCheckRunnable
# void onCreate(Bundle)
- void initViews()
- void setupMusic()
- void initDimensions()
+ void startTransition()
- void startFadeInSlideUp()
- void checkUserStatus()
- void handleLoadError()
- void navigateToMain()
- void navigateToLogin()
- void startActivityWithClearStack(Intent)
- void restoreVolume()
# void onDestroy()
}


interface com.example.tutorialgame.engine.interfaces.StaticObjectData {
~ Bitmap getBitmap()
~ int getHitboxWidth()
~ int getHitboxHeight()
~ int getHitboxRoof()
}

class com.example.tutorialgame.components.MovementComponent {
- RectF tempHitbox
- Character self
- RectF selfHitbox
- Point[] tileCords
- float kbX
- {static} float KB_FRICTION
- {static} float KB_THRESHOLD
+ void moveInDir(float,GameMap)
+ void applyMovement(float,float,GameMap)
+ boolean canMoveTo(float,float,GameMap)
- boolean isBlockedByElevation(Character,Entity)
+ float applyKnockback(float,float,int,float,float)
+ void applyRecoil(float,float,float)
+ void update(double,GameMap)
+ boolean isKnockbackActive()
+ void cancelKnockback()
}


class com.example.tutorialgame.gamestates.menu.menustates.MusicSoundsMenu {
- CustomSeekBar sbMusic
- RectButton btnDone
- CustomSwitch swHaptics
+ void onEnter()
- void refreshSettings()
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ void onProgressChanged(CustomSeekBar,float)
}


class com.example.tutorialgame.ui.activities.authentication.LoginActivity {
- {static} int REQ_READ_PHONE_STATE
- FirebaseAuth mAuth
- TextInputEditText etEmail
- Button btnLogin
- TextView tvRegisterNow
- ProgressBar progressBar
# void onCreate(Bundle)
- void initViews()
- void initData(Intent)
- void initListeners()
- void initTextWatcher()
+ void onClick(View)
- void loginUser()
- void resetPassword()
- void askPermission()
}


class com.example.tutorialgame.gamestates.cutscenes.scenes.GettingSword {
}
class com.example.tutorialgame.environments.maploder.ObjectData {
+ String name
+ String type
+ PointF position
+ RectF bounds
+ String connectsTo
+ String targetDoor
+ String requiredCheckPoint
+ float radius
+ int color
+ LightSource.LightType lightType
+ void setLightProperties(float,int,LightSource.LightType)
}


enum com.example.tutorialgame.engine.ui.customviews.buttons.rects.RectImages {
+  REPLAY
+  EXIT_DEATH
+  EXIT_MENU
+  BACK
+  RETURN
+  OPTIONS
+  DONE
+  VIDEO_SETTINGS
+  MUSIC_SOUNDS
+  LANGUAGE
+  CREDITS
- NinePatchDrawable normal
- int textRes
- TextRenderer textPaint
+ NinePatchDrawable getNormal()
+ NinePatchDrawable getPressed()
+ String getText()
+ void setTextPos(boolean)
+ TextRenderer getTextPaint()
}


class com.example.tutorialgame.engine.ui.joystick.Joystick {
- PointF centerPos
- float radius
- Paint paintOuter
- int pointerId
- boolean pushed
- PointF movementVector
+ void draw(Canvas)
+ void eventHandler(MotionEvent)
- void updatePositions(float,float)
+ void reset()
- boolean isInside(float,float)
+ PointF getMovementVector()
+ boolean isPushed()
}


class com.example.tutorialgame.gamestates.menu.menustates.VideoSettingsMenu {
- RectButton btnDone
- CustomSeekBar sbZoom
- CustomRadioGroup radioTapEffects
- CustomSwitch swFPS
+ void onSelectionChanged(CustomRadioGroup,int)
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
}


class com.example.tutorialgame.engine.renderer.TileRenderer {
+ void drawTiles(Canvas,GameMap)
- void drawLayer(Canvas,GameMap,int,int,int,int,int,boolean)
}

abstract class com.example.tutorialgame.ui.base.BaseActivity {
# {static} SharedPreferences spSettings
- {static} String lang
- Toast lastToast
- Paint errorPaint
- long lastBackPress
- int backPressCount
- {static} boolean DOES_VIBE
- {static} Context currentActivityContext
+ {static} Context updateLocale(Context,String)
+ {static} Context getContext()
# void attachBaseContext(Context)
# void onCreate(Bundle)
# void onResume()
# void onPause()
# void onDestroy()
+ {static} void ButtonPressVibe()
+ {static} void setDoesVibe(boolean)
+ {static} SharedPreferences getSpSettings()
+ void onWindowFocusChanged(boolean)
- void hideSystemUI()
+ void showToast(String,int)
# void setError(EditText,String,int)
# void setupBackPressHandler()
# void handleExitWithDoubleClick()
+ {static} String getLang()
}


abstract class com.example.tutorialgame.engine.ui.effects.weathereffects.WeatherEffect {
# Random random
# Paint paint
# float x
# float speedX
# int alpha
# boolean fading
+ {abstract}RenderOrder getRenderOrder()
# {abstract}void init(float,float)
+ {abstract}void update(double)
+ {abstract}void draw(Canvas)
# void applyMovement(double)
+ boolean isDead()
+ void respawn(float,float)
}


enum com.example.tutorialgame.engine.ui.effects.weathereffects.RenderOrder {
+  BELOW_ENTITIES
+  ABOVE_ENTITIES
}

abstract class com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.Fighter {
- boolean isDuelActive
+ void update(double,GameMap)
+ void startChallenge(Character)
- void checkDuelStatus(Character)
+ void endDuel(boolean)
}


class com.example.tutorialgame.engine.audio.SoundManager {
- {static} String TAG
- {static} long SAVE_DELAY_MS
- {static} SoundManager instance
- SoundPool soundPool
- Context appContext
- Map<Integer,Integer> resIdToSoundId
- Set<Integer> loadedSoundIds
- Random rnd
- float minRate
- float maxRate
- Handler saveHandler
- SharedPreferences sp
- float soundVolume
- Runnable saveRunnable
+ {static} SoundManager getInstance(Context)
+ void loadAllSfx(int[])
+ boolean isLoaded(int)
+ void playRndPitchSfx(int)
+ void playSpatialSfx(int,float)
+ void playSfx(int)
+ void setVolume(float,boolean)
+ void setVolume(float)
+ float getVolume()
+ void persistVolumeNow()
+ void release()
- float clamp(float)
}


class com.example.tutorialgame.managers.BitmapManager {
- {static} String TAG
- {static} BitmapMethods helper
- {static} Map<String,Bitmap> bitmapCache
- {static} Map<String,Bitmap[]> sheetCache
- {static} Map<String,Bitmap[][]> sheet2DCache
- {static} Map<Integer,Bitmap> rawAtlasCache
- {static} String getCacheKey(int,double,boolean)
- {static} Bitmap getRawAtlas(int)
+ {static} Bitmap getBitmap(int)
+ {static} Bitmap getBitmap(int,double,boolean)
+ {static} Bitmap getBitmapRegion(int,int,int,int,int,double,boolean)
+ {static} Bitmap[] getSpritesheet(int,int,int,int,double,boolean)
+ {static} Bitmap[] getSpritesheet(int,int,int,int,double,boolean,boolean)
+ {static} Bitmap[][] getSpritesheet2D(int,int,int,int,int,double,boolean)
+ {static} void clearCache()
}


class com.example.tutorialgame.engine.renderer.LightRenderer {
- {static} float SCALE_DOWN
- {static} int QUANTIZE_STEP
- Bitmap lightmapBitmap
- Canvas lightmapCanvas
- LinkedHashMap<Integer,Bitmap> whiteMaskCache
- RectF dstRect
- Rect screenRect
- Paint addLightPaint
- Paint screenMultiplyPaint
- Paint directGlowPaint
- LightSource[] visibleLights
- int visibleCount
+ void render(Canvas,GameMap)
- void drawGlowDirectlyToScreen(Canvas,LightSource,float,float,float)
- void collectVisibleLights(List<LightSource>,float,float,float)
- void drawLightToMap(LightSource,float,float,float)
- void drawPlayerLightToMap(Player,float,float,float)
- Bitmap getWhiteMask(int)
- int quantize(int)
}


enum com.example.tutorialgame.engine.ui.customviews.buttons.ButtonImages {
+  PLAYING_MENU
+  MENU_REPLAY
- int width
- Bitmap normal
+ int getWidth()
+ int getHeight()
+ Bitmap getBtnImg(boolean)
}


class com.example.tutorialgame.utils.ValidationUtils {
+ {static} boolean isEmailValid(String)
+ {static} boolean isPasswordValid(String)
+ {static} boolean isNicknameValid(String)
}

class com.example.tutorialgame.gamestates.playing.playingstates.tictactoe.TicTacToe {
- PlayingManager playingManager
- TicTacToeAI ticTacToeAI
- int[][] board
- RectF[] grid
- boolean aiNeedsToPlay
- int whoPlayed
- float startX
- float cellSize
- Paint linePaint
- Paint paintX
- Paint paintO
- Paint textPaint
- boolean playerWin
- RectButton resetButton
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
}


class com.example.tutorialgame.engine.ui.customviews.upgrade.CustomUpgrade {
- OnUpgradeListener listener
- Upgrades upgradeImg
- CircleFrames circleFrame
- CircleButton btnUpgrade
- PointF upgradeCenter
- RectF bounds
- float containerX
- int countToApply
- float levelX
- boolean isBalloonVisible
- {static} Bitmap container
- {static} Paint levelPaint
- {static} TextRenderer balloonTitleRenderer
- float balloonX
- {static} float balloonWidth
- float titleX
- StaticLayout descriptionLayout
- void initLogic()
- void updateLayout()
- void updatePositions()
+ void setOnUpgradeListener(OnUpgradeListener)
- int calCurrentLevel()
- float getBtnDownY()
- float getBtnUpY()
+ void draw(Canvas)
+ void drawBalloon(Canvas)
- void drawContainer(Canvas)
- void drawButtons(Canvas)
- void drawUpgradeIcon(Canvas)
+ void eventHandler(MotionEvent)
+ void onClick(BaseButton)
+ void update(int,double)
- void setPrice()
+ RectF getBounds()
+ void updateCircleFrame()
+ void setCenter(float,float)
+ PointF getCenter()
+ int getCountToApply()
+ String getStatField()
+ int getUpgradeValue()
+ void resetCountToApply()
+ void setBalloonVisible(boolean)
+ boolean isBalloonVisible()
}


interface com.example.tutorialgame.engine.ui.customviews.upgrade.CustomUpgrade$OnUpgradeListener {
~ boolean onUpgradeChanged(CustomUpgrade,int)
}

class com.example.tutorialgame.cloud.document.WorldStateDoc {
- String lastMap
- PointF lastPosition
- Map<String,Boolean> storyFlags
# String getDocName()
# void parseData(Map<String,Object>)
+ void createDefaults()
- void defaultStoryFlags()
- String getVisualCheckpointKey()
+ void saveWorldState()
+ void setCheckPoint(String)
+ String getLastMap()
+ PointF getLastPosition()
+ Weapons getCurrentWeapon()
+ boolean getCheckPoint(String)
+ void setCurrentWeapon(String)
}


class com.example.tutorialgame.gamestates.menu.menustates.MainMenu {
- boolean isEntering
- RectButton btnBack
- float offsetY
- {static} float SLIDE_SPEED
+ void onEnter()
- void resetAnimation()
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ void onClick(BaseButton)
}


abstract class com.example.tutorialgame.ui.base.BaseFragment {
# boolean blocksTouches
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
# void replaceFragment(int,Fragment,int,int)
# {abstract}int getLayoutResId()
# {abstract}void onSetupView(View)
}


class com.example.tutorialgame.engine.ui.NpcHealthBar {
- {static} Bitmap lifeBarEmpty
- {static} int barWidth
- {static} Paint flashPaint
- Character npc
- Rect srcRect
- Rect dstRect
- Rect flashSrcRect
- Rect flashDstRect
+ void drawBar(Canvas)
- void drawFlash(Canvas,float,float,int,float,int)
}


enum com.example.tutorialgame.engine.ui.effects.weathereffects.leaves.Leaves {
+  LEAF_GREEN
+  LEAF_PINK
- Bitmap[] sprites
+ Bitmap getSprite(int)
}


class com.example.tutorialgame.engine.renderer.CharacterRenderer {
- Paint shadowPaint
- NpcHealthBar healthBar
- Character character
- {static} Bitmap shadowBitmap
- {static} boolean SHOW_HITBOX
+ void drawFullCharacter(Canvas)
- void drawEmote(Canvas)
- void drawShadow(Canvas)
- void drawCharacter(Canvas)
- void drawHealthBar(Canvas)
+ {static} void setShowHitbox(boolean)
}


class com.example.tutorialgame.components.drop.DropComponent {
- Character character
- DropEntry dropEntry
- Random rnd
+ void dropCoin()
+ void dropXp()
}


class com.example.tutorialgame.managers.WorldEventManager {
+ {static} void triggerEvent(String)
+ {static} void refreshWorldState()
- {static} void moveCharacterToMap(String,String,String,float,float)
+ {static} void setDoorState(String,String,boolean)
}

enum com.example.tutorialgame.entities.foregrounds.breakable.BreakableType {
+  WOODEN_BOX
+  BUSH_1
+  BUSH_2
+  BUSH_3
+  ROCK_1
+  ROCK_2
+  TREE_TRUNK
- Bitmap spr
- BreakParticlesType particles
- boolean canRespawn
- long respawnTime
+ Bitmap getSpr()
+ BreakParticlesType getParticles()
+ int getWidth()
+ int getHeight()
+ boolean canRespawn()
+ long getRespawnTime()
}


class com.example.tutorialgame.gamestates.menu.MenuManager {
- MainMenu mainMenu
- OptionsMenu optionsMenu
- MusicSoundsMenu musicSoundsMenu
- VideoSettingsMenu videoSettingsMenu
- MenuState currentMenuState
- void initMenuStates()
+ void setCurrentMenuState(MenuState)
- BaseMenu getMenuInstance(MenuState)
+ void update(double)
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ void onEnter()
}


enum com.example.tutorialgame.gamestates.menu.MenuState {
+  Main
+  Options
+  MusicSounds
+  VideoSettings
}

class com.example.tutorialgame.components.DialogueComponent {
- List<String> dialogueLines
- int currentLineIndex
+ void updateLines(List<String>)
+ String getNextLine()
+ boolean isEmpty()
}


enum com.example.tutorialgame.engine.ui.PlayerFaceset {
+  IDLE
+  HURT
+  EXHAUSTED
- Bitmap face
+ Bitmap getFace()
}


enum com.example.tutorialgame.ui.dialogs.DialogKeys {
+  PROFILE_EMAIL
+  PROFILE_NICKNAME
+  CHANGE_SLOT
+  CREATE_SLOT
+  SETTINGS_LOGOUT
+  DELETE_SLOT_POSITIVE
+  DELETE_SLOT_NEGATIVE
- int title
- ProfileDoc.Field key
- int inputType
+ ProfileDoc.Field getKey()
+ int getTitle()
+ int getMessage()
+ int getInputType()
+ int getHint()
}


class com.example.tutorialgame.ui.fragments.FramesFragment {
- RecyclerView recyclerView
- ImageButton btnClose
- TextView tvFramesCollected
# int getLayoutResId()
# void onSetupView(View)
- void bindViews(View)
- void setupRecyclerView()
+ void onClick(View)
- void onDataChanged()
}


class com.example.tutorialgame.engine.renderer.TextRenderer {
- TextRenderer shadowRenderer
- float x
+ void drawText(String,Canvas)
+ void drawWithShadow(String,Canvas)
+ void drawWrappedText(Canvas,String,float,float,int)
- void updateShadowPosition()
+ void setShadowColor(int)
+ void setShadowOffset(float,float)
+ void setPosition(float,float)
+ int getShadowColor()
+ void setX(float)
+ void setY(float)
+ float getX()
+ float getY()
+ void updateColorBasedOnValue(int,int,int)
}


class com.example.tutorialgame.entities.characters.enemies.Skeleton {
- long lastDirChange
- Random rand
+ void update(double,GameMap)
# void onIdeal(double,GameMap)
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}


class com.example.tutorialgame.entities.characters.enemies.EyeMonster {
- {static} int globalSoundCount
- {static} long lastGlobalResetTime
- {static} int MAX_GLOBAL_SOUNDS_PER_SEC
- long lastSoundTime
- long lastDirChange
- Random rand
- boolean maxRageSoundPlayed
- {static} float FOV_ANGLE
- {static} float PLAYER_VISION_RANGE
+ void update(double,GameMap)
- void handleScarySounds()
- boolean isPlayerLookingAtMe(Player)
+ void setCharacterDead()
# void onAggressive(double,GameMap)
# void onIdeal(double,GameMap)
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
+ int getAniIndex()
}


abstract class com.example.tutorialgame.entities.characters.Npc {
# State currentState
# boolean preparingAttack
# long timerBeforeAttack
# long timeToAttack
# long lastTimeSeenPlayer
# Character currentTarget
# float baseSpeed
- long lastTargetCheckTime
- {static} long TARGET_CHECK_INTERVAL
- float camShakeMagnitude
+ void update(double,GameMap)
# void onRetreat(double,GameMap)
- void checkCurrentTarget(double,GameMap)
# void onAggressive(double,GameMap)
# void onIdeal(double,GameMap)
# void findTargetClap(GameMap)
# void setPlayerSpeaker(GameMap)
# boolean isCloseToPlayer(GameMap)
- Character findTarget(GameMap)
# void forgetOldTargets(long)
# Character findClosestTarget()
# void processAttack()
+ void prepareAttack(Character)
# void updateAttackTimer()
# void checkTimeToAttackTimer()
+ boolean isPreparingAttack()
}


enum com.example.tutorialgame.entities.characters.State {
+  IDEAL
+  AGGRESSIVE
+  RETREAT
}

class com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.FighterWhite {
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

class com.example.tutorialgame.gamestates.playing.playingstates.tictactoe.TicTacToeAI {
- int SIZE
- int[][] board
+ {static} int PLAYER
+ {static} int COMPUTER
- {static} Integer INF
+ void markSquare(int,int,int)
+ boolean isAvailableSquare(int,int)
+ boolean isBoardFull()
+ boolean checkWin(int)
- float miniMax(int,int,float,float)
+ int[] findBestMove()
+ void resetBoard()
}


class com.example.tutorialgame.engine.core.GamePanel {
- Game game
+ boolean onTouchEvent(MotionEvent)
+ Game getGame()
+ void pauseGame()
+ void resumeGame()
+ void surfaceCreated(SurfaceHolder)
+ void surfaceChanged(SurfaceHolder,int,int,int)
+ void surfaceDestroyed(SurfaceHolder)
}


class com.example.tutorialgame.engine.ui.effects.MapTransitionEffect {
- State currentState
- float circleRadius
- float maxRadius
- Path path
- {static} float SPEED
- {static} PointF targetPos
+ void startClosing()
+ void startOpening()
+ void update(double)
+ void draw(Canvas)
- void updateTargetPos()
+ boolean isFullyClosed()
+ State getCurrentState()
}


enum com.example.tutorialgame.engine.ui.effects.State {
+  IDLE
+  CLOSING
+  OPENING
}

class com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter {
- List<CircleFrameSeries> seriesList
- SparseArray<FramesAdapter> childAdapters
- int selectedSeriesPosition
- int selectedFramePosition
- Runnable globalRefreshTask
- void findInitialSelection()
+ void onDataChanged(int)
+ SeriesViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(SeriesViewHolder,int)
+ int getItemCount()
}


interface com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter$FrameSelectionListener {
~ void onFrameSelectionChanged(int,int)
}

class com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter$SeriesViewHolder {
~ TextView seriesName
~ RecyclerView framesRecyclerView
- void bind(CircleFrameSeries,int,FrameSelectionListener,FramesAdapter.OnDataChangedListener)
}


class com.example.tutorialgame.components.AnimationComponent {
- int aniTick
- int frameCount
- int speed
+ boolean update()
+ int getAniIndex()
+ void setAniIndex(int)
+ void resetAnimation()
+ void setSpeed(int)
+ int getSpeed()
+ void setFrameCount(int)
}


class com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.FighterRed {
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}

class com.example.tutorialgame.gamestates.playing.playingstates.DialogState {
- PlayingManager playingManager
- DialoguePanel dialoguePanel
- Character lastSpeaker
- PointF focusPoint
- Paint letterboxPaint
- {static} float MAX_CINEMATIC_ZOOM
- float elapsedTime
- {static} float ZOOM_DURATION
- DialogueComponent currentDialogue
- {static} boolean isEnding
+ void onEnter()
+ void onExit()
+ void update(double)
- void updateFocusPoint()
+ void render(Canvas)
+ void touchEvents(MotionEvent)
+ void setCurrentSpeaker(Character)
+ void setCurrentSpeaker(Character,String)
+ void setCurrentSpeakerWithLines(Character,List<String>)
- void prepareSpeaker(Character)
+ void continueLastDialog()
+ {static} void endDialogue(String)
+ String getNextDialogueLine()
- float easeInOutCubic(float,float,float,float)
+ PlayingManager getPlayingManager()
}


class com.example.tutorialgame.entities.foregrounds.breakable.BrokenParticle {
- float x
- float velX
- float alpha
- Bitmap img
- boolean active
- float lifeTimer
- Paint paint
- {static} float GRAVITY
- Random r
+ void init(float,float,Bitmap)
+ void update(double)
+ void draw(Canvas)
+ boolean isActive()
}


abstract class com.example.tutorialgame.gamestates.BaseState {
# Game game
# Context context
- Intent intent
+ Game getGame()
- void finishGameActivity()
# void returnLauncher()
+ void onEnter()
+ void onExit()
}


enum com.example.tutorialgame.entities.foregrounds.statics.GameObjects {
+  PILLAR_YELLOW
+  STATUE_ANGRY_YELLOW
+  MONK_STATUE_BALL_YELLOW
+  MONK_STATUE_YELLOW
+  SOLDIER_SPEAR_YELLOW
+  PLANTER_STICKS_YELLOW
+  CUBE_YELLOW
+  FROG_YELLOW
+  SOLDIER_SWORD_YELLOW
+  PILLAR_SHORT_YELLOW
+  PILLAR_SNOW_YELLOW
+  PILLAR_GREEN
+  STATUE_ANGRY_GREEN
+  MONK_STATUE_BALL_GREEN
+  MONK_STATUE_GREEN
+  SOLDIER_SPEAR_GREEN
+  PLANTER_STICKS_GREEN
+  CUBE_GREEN
+  FROG_GREEN
+  SOLDIER_SWORD_GREEN
+  PILLAR_SHORT_GREEN
+  PILLAR_SNOW_GREEN
+  POT_ONE_FULL
+  POT_ONE_EMPTY
+  POT_TWO_FULL
+  POT_TWO_EMPTY
+  BASKET_FULL_RED_FRUIT
+  BASKET_FULL_CHICKEN
+  BASKET_EMPTY
+  BASKET_FULL_BREAD
+  OVEN_SNOW_YELLOW
+  OVEN_YELLOW
+  OVEN_GREEN
+  STOMP
+  SMALL_POT_FULL
+  SMALL_POT_EMPTY
+  WEAPON_BENCH_1
+  WEAPON_BENCH_2
+  ANVIL
+  BENCH_FRONT
+  BENCH_SIDE
+  WEAPONS_BASKET
+  WORK_DESK
- Bitmap objectImg
- int width
- int hitboxRoof
- int hitboxHeight
+ int getHitboxHeight()
+ int getHitboxWidth()
+ Bitmap getBitmap()
+ int getHitboxRoof()
}


enum com.example.tutorialgame.entities.foregrounds.statics.Buildings {
+  HOUSE_ONE
+  HOUSE_TWO
+  HOUSE_THREE
+  DOJO
+  RESTAURANT
+  BAKERY
+  MAIL_STATION
+  WEAPON_STORE
+  CHIEF_HOUSE_TOP
+  CHIEF_HOUSE_BOTTOM
~ Bitmap houseImg
~ PointF doorwayPoint
~ int hitboxRoof
+ PointF getDoorwayPoint()
+ Bitmap getBitmap()
+ int getHitboxWidth()
+ int getHitboxHeight()
+ int getHitboxRoof()
}


class com.example.tutorialgame.engine.ui.customviews.CustomSeekBar {
- OnProgressChangedListener listener
- RectF bgHitbox
- NinePatchDrawable normal
- TextRenderer percentRenderer
- float percentY
- String name
- boolean pushed
- float progress
- String percentText
- float percentX
- int currentPercent
- int colorPushedText
- int colorNormalText
+ void setOnProgressChangedListener(OnProgressChangedListener)
- NinePatchDrawable getSeekBarImg()
+ void setProgressNormalized(float)
- void seekBarEffects()
- void setProgressFromX(float)
- void updateDrawableBoundsFromProgress()
- void updatePercentCache()
+ float eventHandler(MotionEvent)
+ void drawSeekBar(Canvas)
- void drawText(Canvas)
- void drawSeekBarName(Canvas,float)
- void drawPercentsText(Canvas,float)
- boolean isIn(MotionEvent)
}


interface com.example.tutorialgame.engine.ui.customviews.CustomSeekBar$OnProgressChangedListener {
~ void onProgressChanged(CustomSeekBar,float)
}

class com.example.tutorialgame.ui.fragments.ProfileFragment {
- ImageView ivFrame
- Button btnNickname
- TextView tvLevel
- CustomDialog dialogEditEmail
- View slot1
# int getLayoutResId()
# void onSetupView(View)
- void initPrefs()
- void updateSlotsUI()
- void setupSlotView(int)
- View getSlotRoot(int)
- void showRenameDialog(int,String)
- void handleSlotSelection(int)
- void handleDeleteSlot(int)
- void handleNewSlotCreation(int)
- void bindViews(View)
- void initListeners()
+ void onClick(View)
}


class com.example.tutorialgame.MyApp {
- {static} Context appContext
- {static} CloudManager cloudManager
- {static} GamePanel gamePanel
+ void onCreate()
+ {static} void initializeCloudManager()
+ {static} void startLoadingAccountData(UserDataManager.OnDataLoadedListener)
+ {static} void clearCloudManager()
+ void onTrimMemory(int)
+ {static} Context getAppContext()
+ {static} CloudManager getCloudManager()
+ {static} ProfileDoc getProfile()
+ {static} StatsDoc getPlayerStats()
+ {static} ProgressDoc getProgress()
+ {static} CosmeticDoc getCosmetic()
+ {static} WorldStateDoc getWorldStateDoc()
+ {static} void setGamePanel(GamePanel)
+ {static} GamePanel getGamePanel()
}


class com.example.tutorialgame.components.JumpComponent {
- float elevation
- float vz
- float gravity
- float jumpVelocity
- float maxElevation
- long jumpStartTime
- OnLandListener landListener
- void initFromTiles(float,float)
+ void update(double)
+ void setOnLandListener(OnLandListener)
+ void startJump()
+ float getElevation()
+ float getJumpFraction()
+ boolean isAirborne()
+ long getJumpStartTime()
+ void setGravity(float)
+ float getGravity()
+ void setJumpVelocity(float)
+ float getJumpVelocity()
}


interface com.example.tutorialgame.components.JumpComponent$OnLandListener {
~ void onLand()
}

class com.example.tutorialgame.engine.ui.displays.XpDisplay {
- {static} double SCALE_RATIO
- {static} Bitmap xpImg
- Rect srcRect
- float x
- TextRenderer lv
- double currentXP
- int progWidth
+ void draw(Canvas)
- void drawXpImg(Canvas)
- void drawContainer(Canvas)
- void updateProgress()
}


class com.example.tutorialgame.environments.maploder.MapLoadData {
+ String fileName
+ int[][] groundLayer
+ int[][] wallsLayer
+ int[][] collisionLayer
+ int[][] surfaceLayer
+ List<ObjectData> buildingLayer
+ List<ObjectData> fenceLayer
+ List<ObjectData> characterLayer
+ List<ObjectData> natureLayer
+ List<ObjectData> itemLayer
+ List<ObjectData> objectLayer
+ List<ObjectData> doorLayer
+ List<ObjectData> lightLayer
+ List<ObjectData> animatedLayer
+ List<ObjectData> breakableLayer
+ List<ObjectData> triggerLayer
+ List<TilesetData> tilesets
+ int ambientDarkness
+ String musicFile
+ String spawnType
+ int minMonsters
}

class com.example.tutorialgame.components.EmoteComponent {
- Emotes activeEmote
- float lifeTimer
- float displayDuration
- Character character
- float currentScale
- float offsetY
- float offsetX
- Matrix drawMatrix
+ void update(double)
+ void showEmote(Emotes,long)
+ boolean isActive()
+ void drawEmote(Canvas)
}


class com.example.tutorialgame.cloud.document.StatsDoc {
+ {static} String DOC_NAME
+ {static} String KEY_ROOT
+ {static} String F_MAX_HEALTH
+ {static} String F_STRENGTH
+ {static} String F_ATTACK_SPEED
+ {static} String F_MAX_STAMINA
+ {static} int INIT_HEALTH
+ {static} int INIT_STRENGTH
+ {static} int INIT_ATTACK_SPEED
+ {static} int INIT_STAMINA
- int maxHealth
- int strength
- int attackSpeed
- int maxStamina
# void parseData(Map<String,Object>)
# String getDocName()
+ void createDefaults()
+ void updateStat(String,int,int,int)
+ int getMaxHealth()
+ int getStrength()
+ int getAttackSpeed()
+ int getMaxStamina()
}


abstract class com.example.tutorialgame.entities.characters.nonenemies.NonEnemy {
# float legalOffset
- {static} long TIME_TO_LOOK_DOWN
# long lastTimeAggressive
+ void update(double,GameMap)
# void onIdeal(double,GameMap)
# void goHome(double,GameMap)
# boolean isHome()
# void reverseDamage(double)
}


class com.example.tutorialgame.engine.ui.customviews.radiogroup.CustomRadioGroup {
- OnSelectionChangedListener listener
- Context context
- CircleButton[] radioButtons
- CircleButton selectedButton
- int selectedIndex
- TextRenderer labelRenderer
- int colorNormal
- SharedPreferences settingsPreferences
- String key
- RadioGroupList radioGroupEnum
- NinePatchDrawable background
- float spacing
+ void setOnSelectionChangedListener(OnSelectionChangedListener)
- void setBackground(float,float)
- void setInitialButton()
+ void render(Canvas)
- void drawTitle(Canvas)
- void drawButtons(Canvas)
+ void eventHandler(MotionEvent)
+ Rect getHitbox()
}


interface com.example.tutorialgame.engine.ui.customviews.radiogroup.CustomRadioGroup$OnSelectionChangedListener {
~ void onSelectionChanged(CustomRadioGroup,int)
}

enum com.example.tutorialgame.engine.ui.Emotes {
+  HEART
+  BROKEN_HEART
+  SAD
+  SURPRISED
+  DIALOGUE
+  ANGRY
+  SCARED_AS_HELL
+  COCKY
- Bitmap emote
+ Bitmap getEmote()
}


class com.example.tutorialgame.engine.ui.effects.weathereffects.leaves.Leaf {
- Leaves leafType
- AnimationComponent animator
- float driftIntensity
- float driftFrequency
- double randomOffset
- int cycles
+ RenderOrder getRenderOrder()
# void init(float,float)
+ void update(double)
+ void draw(Canvas)
}


enum com.example.tutorialgame.engine.ui.customviews.upgrade.Upgrades {
+  HEALTH
+  STRENGTH
+  STAMINA
+  ATTACK_SPEED
- Bitmap upgradeImg
- String statField
- int upgradeValue
- double defaultValue
+ Bitmap getUpgradeImg()
+ String getStatField()
+ int getUpgradeValue()
+ int getCurrentStatValue()
+ double getDefaultValue()
+ String getText()
+ String getDescription()
}


enum com.example.tutorialgame.engine.ui.HealthIcons {
+  HEART_FULL
+  HEART_3Q
+  HEART_HALF
+  HEART_1Q
+  HEART_EMPTY
- Bitmap icon
+ Bitmap getIcon()
}


class com.example.tutorialgame.cloud.document.CosmeticDoc {
- {static} String KEY_ROOT
- {static} String KEY_COINS
- {static} String KEY_CURRENT_FRAME
- {static} String KEY_AVAILABLE_FRAMES
- {static} int DEFAULT_COINS
- {static} String DEFAULT_FRAME
- int coinsLeft
- String currentFrame
- List<String> availableFrames
# void parseData(Map<String,Object>)
# String getDocName()
+ void createDoc()
+ boolean purchase(int)
+ void addCoin()
+ void increaseCoins(int)
+ void addAvailableFrame(String)
+ void setCurrentFrame(String)
+ List<String> getAvailableFrames()
+ boolean isFrameAvailable(String)
+ int getCoinsLeft()
+ String getCurrentFrame()
}


class com.example.tutorialgame.entities.characters.nonenemies.neutral.WhiteKnight {
- boolean angry
+ void update(double,GameMap)
+ void onDialogue()
+ void setAngry(boolean)
# void updateAttackTimer()
+ Weapons getWeapon()
+ int getAttackDamage()
# int getHealth()
# int getStamina()
# int getStaminaCoolDown()
+ int getImpactSfx()
+ DropEntry getDropEntry()
+ float getTimeToApexSec()
+ float getDesiredTiles()
}


abstract class com.example.tutorialgame.entities.characters.Character {
# float homeX
# int faceDir
# GameCharacters gameCharType
# boolean moving
# long now
# float viewDistance
- Map<Character,Long> badBoyList
# HealthComponent health
# StaminaComponent stamina
# AnimationComponent animation
# JumpComponent jumpComponent
# MovementComponent movementComponent
# DialogueComponent dialogueComponent
# CombatComponent combatComponent
# EmoteComponent emoteComponent
# DropComponent drop
- CharacterRenderer characterRenderer
- RectF projectedHitBox
- Handler uiHandler
- {static} int DEATH_STEP_DELAY_MS
- int deathStep
# int diedBy
- boolean hasRage
- Runnable deathRunnable
+ void init(PointF)
# Map<Character,Long> getBadBoyList()
+ void update(double,GameMap)
+ void turnTowardsTarget(Character)
+ void draw(Canvas)
+ void damageCharacter(Character)
+ void takeDamage(int,Character)
+ boolean canDamage(Character)
+ boolean isDead()
+ void setCharacterDead()
+ void checkCharacterDead(Character)
+ {abstract}Weapons getWeapon()
+ {abstract}int getAttackDamage()
# {abstract}int getHealth()
# {abstract}int getStamina()
# {abstract}int getStaminaCoolDown()
+ {abstract}int getImpactSfx()
+ {abstract}DropEntry getDropEntry()
+ {abstract}float getTimeToApexSec()
+ {abstract}float getDesiredTiles()
+ void setJumping(boolean)
+ void setAttacking(boolean)
+ void moveToMap(String,float,float)
+ void teleportTo(float,float)
+ void setHome(float,float)
- void updateProjectedHitBox()
+ boolean isJumping()
+ boolean isAttacking()
+ boolean isDamaged()
+ boolean hasRage()
+ float getRagePercentage()
+ HealthComponent getHealthComponent()
+ CombatComponent getCombatComponent()
+ MovementComponent getMovementComponent()
+ int getCurrentHealth()
+ int getMaxHealth()
+ int getFaction()
+ int getFaceDir()
+ void setFaceDir(int)
+ GameCharacters getGameCharType()
+ RectF getProjectedHitBox()
+ boolean isAirborne()
+ float getElevation()
+ RectF getAttackBox()
+ float getJumpFraction()
+ float getViewDistance()
+ EmoteComponent getEmoteComponent()
+ StaminaComponent getStaminaComponent()
+ void setWeapon(Weapons)
+ DialogueComponent getDialogueComponent()
+ int getDiedBy()
+ void setMoving(boolean)
+ int getAniIndex()
+ void resetAnimation()
+ void onDialogue()
}


class com.example.tutorialgame.engine.ui.customviews.buttons.circles.CircleButton {
- Bitmap normal
- Bitmap getImg()
+ RectF getHitbox()
# boolean isIn(float,float)
+ void draw(Canvas)
}




com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.document.ProgressDoc
com.example.tutorialgame.entities.characters.nonenemies.allies.Ally <|-- com.example.tutorialgame.entities.characters.nonenemies.allies.Blacksmith
com.example.tutorialgame.engine.ui.OnClickListener <|.. com.example.tutorialgame.engine.ui.PlayingUI
com.example.tutorialgame.engine.ui.circleframes.Adapter <|-- com.example.tutorialgame.engine.ui.circleframes.FramesAdapter
com.example.tutorialgame.engine.ui.circleframes.FramesAdapter +.. com.example.tutorialgame.engine.ui.circleframes.FramesAdapter$OnDataChangedListener
com.example.tutorialgame.engine.ui.circleframes.FramesAdapter +.. com.example.tutorialgame.engine.ui.circleframes.FramesAdapter$FrameViewHolder
com.example.tutorialgame.engine.ui.circleframes.ViewHolder <|-- com.example.tutorialgame.engine.ui.circleframes.FramesAdapter$FrameViewHolder
com.example.tutorialgame.managers.MapManager +.. com.example.tutorialgame.managers.MapManager$OnMapReadyListener
com.example.tutorialgame.gamestates.OnUpgradeListener <|.. com.example.tutorialgame.gamestates.UpgradeState
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.UpgradeState
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.effects.LevelUpEffect
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.displays.CoinDisplay
com.example.tutorialgame.entities.characters.Character <|-- com.example.tutorialgame.entities.characters.Player
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.cutscenes.SceneManager
com.example.tutorialgame.engine.interfaces.StaticEntity <|.. com.example.tutorialgame.entities.foregrounds.statics.StaticObject
com.example.tutorialgame.entities.Entity <|-- com.example.tutorialgame.entities.foregrounds.statics.StaticObject
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.effects.weathereffects.Cloud
com.example.tutorialgame.engine.ui.effects.weathereffects.WeatherEffect <|-- com.example.tutorialgame.engine.ui.effects.weathereffects.Cloud
com.example.tutorialgame.managers.objectpool.ObjectPoolManager +.. com.example.tutorialgame.managers.objectpool.ObjectPoolManager$RespawnTask
com.example.tutorialgame.ui.fragments.OnClickListener <|.. com.example.tutorialgame.ui.fragments.LanguageFragment
com.example.tutorialgame.ui.base.BaseFragment <|-- com.example.tutorialgame.ui.fragments.LanguageFragment
com.example.tutorialgame.gamestates.menu.menustates.OnClickListener <|.. com.example.tutorialgame.gamestates.menu.menustates.OptionsMenu
com.example.tutorialgame.gamestates.menu.BaseMenu <|-- com.example.tutorialgame.gamestates.menu.menustates.OptionsMenu
com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton <|-- com.example.tutorialgame.engine.ui.customviews.buttons.rects.RectButton
com.example.tutorialgame.gamestates.cutscenes.BaseScene <|-- com.example.tutorialgame.gamestates.cutscenes.scenes.Intro
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.DialoguePanel
com.example.tutorialgame.entities.characters.Npc <|-- com.example.tutorialgame.entities.characters.enemies.Enemy
com.example.tutorialgame.ui.base.BaseActivity <|-- com.example.tutorialgame.ui.activities.GameActivity
com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.document.ProfileDoc
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.effects.impcateffects.TapEffect
com.example.tutorialgame.gamestates.cutscenes.BaseScene <|-- com.example.tutorialgame.gamestates.cutscenes.scenes.SkeletonArise
com.example.tutorialgame.entities.characters.nonenemies.allies.Ally <|-- com.example.tutorialgame.entities.characters.nonenemies.allies.BestFriend
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.playing.PlayingManager
com.example.tutorialgame.ui.activities.OnClickListener <|.. com.example.tutorialgame.ui.activities.LauncherActivity
com.example.tutorialgame.ui.base.BaseActivity <|-- com.example.tutorialgame.ui.activities.LauncherActivity
com.example.tutorialgame.entities.characters.nonenemies.NonEnemy <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral
com.example.tutorialgame.entities.Entity <|-- com.example.tutorialgame.entities.foregrounds.breakable.BreakableEntity
com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton +.. com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton$OnClickListener
com.example.tutorialgame.entities.Entity <|-- com.example.tutorialgame.entities.foregrounds.animated.AnimatedObject
com.example.tutorialgame.entities.Comparable <|.. com.example.tutorialgame.entities.Entity
com.example.tutorialgame.gamestates.OnClickListener <|.. com.example.tutorialgame.gamestates.DeathScreen
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.DeathScreen
com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.BlackKnight
com.example.tutorialgame.entities.foregrounds.animated.AnimatedObject <|-- com.example.tutorialgame.entities.foregrounds.animated.Coin
com.example.tutorialgame.cloud.UserDataManager +.. com.example.tutorialgame.cloud.UserDataManager$OnDataLoadedListener
com.example.tutorialgame.entities.characters.nonenemies.allies.Ally <|-- com.example.tutorialgame.entities.characters.nonenemies.allies.Master
com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.Father
com.example.tutorialgame.engine.core.GameConstants +.. com.example.tutorialgame.engine.core.GameConstants$Face_Dir
com.example.tutorialgame.engine.core.GameConstants +.. com.example.tutorialgame.engine.core.GameConstants$Sprite
com.example.tutorialgame.engine.core.GameConstants +.. com.example.tutorialgame.engine.core.GameConstants$Animation
com.example.tutorialgame.engine.core.GameConstants +.. com.example.tutorialgame.engine.core.GameConstants$View
com.example.tutorialgame.engine.core.GameConstants +.. com.example.tutorialgame.engine.core.GameConstants$Faction
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.menu.BaseMenu
com.example.tutorialgame.ui.activities.authentication.OnClickListener <|.. com.example.tutorialgame.ui.activities.authentication.RegisterActivity
com.example.tutorialgame.ui.base.BaseActivity <|-- com.example.tutorialgame.ui.activities.authentication.RegisterActivity
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.cutscenes.BaseScene
com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.SaveSlotMetadata
com.example.tutorialgame.cloud.SaveSlotMetadata +.. com.example.tutorialgame.cloud.SaveSlotMetadata$Slot
com.example.tutorialgame.entities.characters.nonenemies.NonEnemy <|-- com.example.tutorialgame.entities.characters.nonenemies.allies.Ally
com.example.tutorialgame.engine.core.Runnable <|.. com.example.tutorialgame.engine.core.GameLoop
com.example.tutorialgame.engine.ui.customviews.switches.CustomSwitch +.. com.example.tutorialgame.engine.ui.customviews.switches.CustomSwitch$OnCheckedChangeListener
com.example.tutorialgame.ui.fragments.OnTouchListener <|.. com.example.tutorialgame.ui.fragments.SettingsFragment
com.example.tutorialgame.ui.fragments.OnSeekBarChangeListener <|.. com.example.tutorialgame.ui.fragments.SettingsFragment
com.example.tutorialgame.ui.fragments.OnClickListener <|.. com.example.tutorialgame.ui.fragments.SettingsFragment
com.example.tutorialgame.ui.base.BaseFragment <|-- com.example.tutorialgame.ui.fragments.SettingsFragment
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.playing.playingstates.OverWorld
com.example.tutorialgame.ui.base.BaseActivity <|-- com.example.tutorialgame.ui.activities.SplashActivity
com.example.tutorialgame.gamestates.menu.menustates.OnProgressChangedListener <|.. com.example.tutorialgame.gamestates.menu.menustates.MusicSoundsMenu
com.example.tutorialgame.gamestates.menu.BaseMenu <|-- com.example.tutorialgame.gamestates.menu.menustates.MusicSoundsMenu
com.example.tutorialgame.ui.activities.authentication.OnClickListener <|.. com.example.tutorialgame.ui.activities.authentication.LoginActivity
com.example.tutorialgame.ui.base.BaseActivity <|-- com.example.tutorialgame.ui.activities.authentication.LoginActivity
com.example.tutorialgame.gamestates.cutscenes.BaseScene <|-- com.example.tutorialgame.gamestates.cutscenes.scenes.GettingSword
com.example.tutorialgame.gamestates.menu.menustates.OnSelectionChangedListener <|.. com.example.tutorialgame.gamestates.menu.menustates.VideoSettingsMenu
com.example.tutorialgame.gamestates.menu.BaseMenu <|-- com.example.tutorialgame.gamestates.menu.menustates.VideoSettingsMenu
androidx.appcompat.app.AppCompatActivity <|-- com.example.tutorialgame.ui.base.BaseActivity
com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.Fighter
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.managers.BitmapManager
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.playing.playingstates.tictactoe.TicTacToe
com.example.tutorialgame.engine.ui.customviews.upgrade.OnClickListener <|.. com.example.tutorialgame.engine.ui.customviews.upgrade.CustomUpgrade
com.example.tutorialgame.engine.ui.customviews.upgrade.CustomUpgrade +.. com.example.tutorialgame.engine.ui.customviews.upgrade.CustomUpgrade$OnUpgradeListener
com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.document.WorldStateDoc
com.example.tutorialgame.gamestates.menu.menustates.OnClickListener <|.. com.example.tutorialgame.gamestates.menu.menustates.MainMenu
com.example.tutorialgame.gamestates.menu.BaseMenu <|-- com.example.tutorialgame.gamestates.menu.menustates.MainMenu
androidx.fragment.app.Fragment <|-- com.example.tutorialgame.ui.base.BaseFragment
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.menu.MenuManager
com.example.tutorialgame.ui.fragments.OnClickListener <|.. com.example.tutorialgame.ui.fragments.FramesFragment
com.example.tutorialgame.ui.base.BaseFragment <|-- com.example.tutorialgame.ui.fragments.FramesFragment
android.text.TextPaint <|-- com.example.tutorialgame.engine.renderer.TextRenderer
com.example.tutorialgame.entities.characters.enemies.Enemy <|-- com.example.tutorialgame.entities.characters.enemies.Skeleton
com.example.tutorialgame.entities.characters.enemies.Enemy <|-- com.example.tutorialgame.entities.characters.enemies.EyeMonster
com.example.tutorialgame.entities.characters.Character <|-- com.example.tutorialgame.entities.characters.Npc
com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.Fighter <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.FighterWhite
com.example.tutorialgame.engine.core.Callback <|.. com.example.tutorialgame.engine.core.GamePanel
android.view.SurfaceView <|-- com.example.tutorialgame.engine.core.GamePanel
com.example.tutorialgame.engine.ui.circleframes.OnDataChangedListener <|.. com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter
com.example.tutorialgame.engine.ui.circleframes.Adapter <|-- com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter
com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter +.. com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter$FrameSelectionListener
com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter +.. com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter$SeriesViewHolder
com.example.tutorialgame.engine.ui.circleframes.ViewHolder <|-- com.example.tutorialgame.engine.ui.circleframes.FrameSeriesAdapter$SeriesViewHolder
com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.Fighter <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.fighter.FighterRed
com.example.tutorialgame.gamestates.BaseState <|-- com.example.tutorialgame.gamestates.playing.playingstates.DialogState
com.example.tutorialgame.engine.interfaces.GameStateInterface <|.. com.example.tutorialgame.gamestates.BaseState
com.example.tutorialgame.engine.ui.customviews.CustomSeekBar +.. com.example.tutorialgame.engine.ui.customviews.CustomSeekBar$OnProgressChangedListener
com.example.tutorialgame.ui.fragments.OnClickListener <|.. com.example.tutorialgame.ui.fragments.ProfileFragment
com.example.tutorialgame.ui.base.BaseFragment <|-- com.example.tutorialgame.ui.fragments.ProfileFragment
android.app.Application <|-- com.example.tutorialgame.MyApp
com.example.tutorialgame.components.JumpComponent +.. com.example.tutorialgame.components.JumpComponent$OnLandListener
com.example.tutorialgame.engine.interfaces.BitmapMethods <|.. com.example.tutorialgame.engine.ui.displays.XpDisplay
com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.document.StatsDoc
com.example.tutorialgame.entities.characters.Npc <|-- com.example.tutorialgame.entities.characters.nonenemies.NonEnemy
com.example.tutorialgame.engine.ui.customviews.radiogroup.CustomRadioGroup +.. com.example.tutorialgame.engine.ui.customviews.radiogroup.CustomRadioGroup$OnSelectionChangedListener
com.example.tutorialgame.engine.ui.effects.weathereffects.WeatherEffect <|-- com.example.tutorialgame.engine.ui.effects.weathereffects.leaves.Leaf
com.example.tutorialgame.cloud.BaseDocument <|-- com.example.tutorialgame.cloud.document.CosmeticDoc
com.example.tutorialgame.entities.characters.nonenemies.neutral.Neutral <|-- com.example.tutorialgame.entities.characters.nonenemies.neutral.WhiteKnight
com.example.tutorialgame.entities.Entity <|-- com.example.tutorialgame.entities.characters.Character
com.example.tutorialgame.engine.ui.customviews.buttons.BaseButton <|-- com.example.tutorialgame.engine.ui.customviews.buttons.circles.CircleButton
@enduml